Repository Mq-b/ModernCpp-ConcurrentProgramming-Tutorial, pull requests merged in 2024-05, with the labels that each got.

#7 继续对 Github 外部仓库的代码片段使用永久链接
  md/03共享数据.md
  md/详细分析/01thread的构造与源码解析.md
Labels: enhancement

#9 遗漏的永久链接更改
  md/03共享数据.md
Labels: enhancement

#10 更新依赖和ci版本，修复ci运行失败bug
  .github/workflows/deploy.yml
  .gitignore
  .vuepress/config.js
  package-lock.json
  package.json
Labels: bug, web

#11 Add xmaike build support
  code/04同步操作/async_progress_bar/xmake.lua
Labels: enhancement, build
